import Head from 'next/head';
import Link from 'next/link';
import axios from 'axios';
import { useEffect, useState } from 'react';
import { request } from '../../api/menu_olsztyn';

export interface ICourse {
	id: string;
	name: string;
	price: Number;
	desc?: string;
}

const apiQuery = `query Home {
    allCourses(first: 99) {
      id
      name
      price
      desc
    }
  }`;

export const getStaticProps = async () => {
	const data = await request({
		query: apiQuery,
		variables: { limit: 59 },
	});

	return {
		props: { data },
	};
};

export default function Home({ data }: any) {
	const [menu, setMenu] = useState<[] | ICourse[]>([]);

	useEffect(() => {
		console.log(data);
		setMenu(data);
	}, []);
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main>
				<header>
					<h1>page - Olsztyn</h1>
					{data.allCourses.length > 0
						? data.allCourses.map(
								({
									id,
									name,
									price,
								}: {
									id: string;
									name: string;
									price: Number;
								}) => (
									<div
										key={id}
										style={{
											display: 'flex',
											justifyContent: 'space-between',
											width: '300px',
										}}>
										<p>{name}</p>
										<p>{String(price)}</p>
									</div>
								)
						  )
						: null}
				</header>
			</main>
		</>
	);
}
