import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main>
				<header>
					<h1>hello</h1>
					<div style={{ display: 'flex', flexDirection: 'column' }}>
						<Link href={`/olsztyn`}>Olsztyn, Żołnierska 4</Link>
						<Link href={`/ketrzyn`}>
							Kętrzyn, Plac marszałka Józefa Piłsudskiego 1
						</Link>
					</div>
				</header>
			</main>
		</>
	);
}
