import Head from 'next/head';
import Link from 'next/link';
import axios from 'axios';
import { useEffect, useState } from 'react';
import { request } from '../api/menu_olsztyn';
import Layout from './layout';

export default function Home() {
	return (
		<>
			<Head>
				<title>Restauracja Kardamon | Olsztyn, Żołnierska 4</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main>
				<header>
					<Layout>
						<h1>page - Olsztyn</h1>
					</Layout>
				</header>
			</main>
		</>
	);
}
